version: "3.9"
services:
  webserver:
    container_name: solar-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: solar-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rooter
      MYSQL_DATABASE: laravel
      MYSQL_USER: db_user
      MYSQL_PASSWORD: rooter
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: solar-myadmin
    links:
      - mysql-db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: rooter
